[server]
port = 8002
host = "0.0.0.0"

[auth]
enable = false
signature_key = "secret_key_for_hmac"

[ota]
firmware_version = "0.9.9"

[ota.mqtt]
enable = false
endpoint = "ssl://mqtt.example.com:8883"

[llm]
provider = "gemini"
api_key = "Key"
model = "gemini-2.0-flash-lite"
history_limit = 5
system_instruction = "你是一個智慧音箱，回復以繁體中文為主，避免過長思考與長篇大論，且避免類似書面語、論文、文檔形式的發言。請用類似人類的隨意語法發言"

[stt]
provider = "local"

[tts]
provider = "gemini"

[tts.gemini]
# api_key = "Optional if different from llm"
model = "gemini-2.5-flash-preview-tts"
voice_name = "Kore"

[db]
type = "memory"
# url = "sqlite://xiaozhi.db"
